YuraRov/vetClinic

Application/Application.csproj, Application/Services/ApplicationServicesConfiguration.cs, DataAccess/DataAccess.csproj, DataAccess/Repositories/ApplicationRepositoriesConfiguration.cs, Host/Host.csproj, Host/Middleware/ApplicationMiddlewareConfiguration.cs, Host/Program.cs
Added ServicesConfiguration, MiddlewareConfiguration,RepositoriesConfiguration
=> Add ConfigurationClasses

Application/Application.csproj, Application/Services/AniamlService.cs, Core/Core.csproj, Core/Entities/Animal.cs, Core/Interfaces/Services/IAnimalService.cs
=> Set up class and (I)service for animal

Application/Application.csproj, Application/Services/ApplicationServicesConfiguration.cs, Application/Services/LoggerManager.cs, Core/Interfaces/ILoggerManager.cs, Host/Nlog.config, Host/Program.cs
Add NuGet, create interface ILoggerManager, class LoggerManager
=> Setup Logger(NLog) and create DI for it

Application/Application.csproj, Application/Services/ProcedureService.cs, Core/Entities/Procedure.cs, Core/Interfaces/Services/IProcedureService.cs
Filled procedure entity, added procedureService class and interface
=> BE OS prosedures add procedure service and interface

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, Core/Interfaces/Services/IUserService.cs, DataAccess/Repositories/UserRepository.cs
Filled User repo and service with methods
=> Filled User repo and service with methods 

Core/Entities/User.cs
Added Specializations navigation property to User
=> Added Specializations navigation property to User

Core/Entities/AppointmentUser.cs, Core/Entities/User.cs, Core/Entities/UserSpecialization.cs
=> Edited User relationships

Core/Entities/Procedure.cs, Core/Entities/ProcedureSpecialization.cs, Core/Entities/Specialization.cs, Core/Interfaces/Repositories/IProcedureRepository.cs, DataAccess/Configurations/ProcedureConfiguration.cs, DataAccess/Configurations/ProcedureSpecializationConfiguration.cs, DataAccess/Context/ClinicContext.cs, DataAccess/Repositories/ApplicationRepositoriesConfiguration.cs, DataAccess/Repositories/ProcedureRepository.cs
Created and configured ProcedureSpecialization, added and implimented (I)ProcedureRepository
=> ProcedureSpecialization and (I)ProcedureRepository

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, Core/Interfaces/Services/IUserService.cs, DataAccess/Configurations/UserConfiguration.cs, DataAccess/Repositories/UserRepository.cs
Configured fluent api for User, changed repo and service
=> Configured fluent api for User, changed repo and service

Core/Interfaces/Repositories/IAddressRepository.cs, Core/Interfaces/Repositories/IPortfolioRepository.cs, DataAccess/Repositories/AddressRepository.cs, DataAccess/Repositories/PortfolioRepository.cs
Please tell me what else I should add to these repository classes. Exception handler or maybe something else? I would really appreciate that.
=> Added Portfolio and Address repository carcass

Application/Services/AddressService.cs, Application/Services/PortfolioService.cs, Core/Interfaces/Services/IAddressService.cs, Core/Interfaces/Services/IPortfolioService.cs
Please tell me what else I should add to these service classes. Exception handler or maybe something else? I would really appreciate that.
=> Added Portfolio and Address service carcasses

Core/DTO/UserCreateDto.cs, Core/DTO/UserDTO.cs, Core/DTO/UserReadDto.cs, Core/DTO/UserUpdateDto.cs, DataAccess/Repositories/UserRepository.cs, Host/Configurations/SystemServicesConfiguration.cs, Host/Host.csproj, Host/Program.cs, WebApi/AutoMapper/UserProfile.cs, WebApi/Controllers/UsersController.cs, WebApi/Validators/UserCreateDtoValidator.cs, WebApi/Validators/UserUpdateDtoValidator.cs, WebApi/WebApi.csproj
Created UsersController with appropriate profile, DTOs and validators
=> Created UsersController with appropriate DTOs and validators

Application/Services/ProcedureService.cs, Core/Core.csproj, Core/Exceptions/BadRequestException.cs, Core/Exceptions/ForbidException.cs, Core/Exceptions/NotFoundException.cs, Core/Exceptions/UnauthorizedException.cs, Core/Interfaces/Repositories/IProcedureRepository.cs, Core/Interfaces/Services/IProcedureService.cs, Core/ViewModels/ProcedureViewModels/ProcedureViewModelBase.cs, DataAccess/Context/ClinicContext.cs, DataAccess/Repositories/ProcedureRepository.cs, Host/Middleware/ExceptionMiddleware.cs, WebApi/Controllers/ExceptionController.cs, WebApi/Controllers/ProcedureController.cs, WebApi/Controllers/SpecializationController.cs
Implemented functionality to assign specializations to procedure
=> Implemented assigning specializations to the procedure

WebApi/Controllers/UsersController.cs
=> Created employee registration

Application/Services/UserService.cs, WebApi/Controllers/UsersController.cs
Removed validators injection from UsersController constructor
=> Removed validators injection from UsersController constructor

Core/Entities/User.cs
Added IsActive property to User
=> Added IsActive property to User

DataAccess/Migrations/20220526160149_InitMigration.Designer.cs, DataAccess/Migrations/20220526160149_InitMigration.cs, DataAccess/Migrations/ClinicContextModelSnapshot.cs
=> Reinited migration once more

WebApi/AutoMapper/UserMappers/UserCreateMapper.cs
Changed User.UserName mapping logic
=> Changed User.UserName mapping logic

Application/Services/ProcedureService.cs, DataAccess/Repositories/ProcedureRepository.cs, WebApi/AutoMapper/Configurations/ApplicationMappersConfiguration.cs, WebApi/Controllers/ProcedureController.cs
Removed redundant null check in GetAll, added Task.CompletedTask to false-async methods
=> Demo fixes

WebApi/Controllers/UserController.cs
Added Authorize attribute to Get request, when getting all the users
=> Added Authorize attribute to Get request, when getting all the users

Application/Services/FinancialService.cs, DataAccess/Repositories/SalaryRepository.cs, WebApi/Controllers/FinancialController.cs, WebApi/Validators/SalaryValidators/SalaryViewModelValidator.cs
deleted unneccessary using
added 2 LogWarn
changed post and put methods to return NoContent()
=> Little fixes before demo

Application/Services/FinancialService.cs, DataAccess/Repositories/SalaryRepository.cs
add exceptions to update and create
=> add exceptions to finance service

Core/Interfaces/Repositories/IUserRepository.cs, Core/ViewModels/User/UserReadViewModel.cs, DataAccess/Repositories/UserRepository.cs, WebApi/AutoMapper/UserMappers/UserReadMapper.cs
Changed user repo, read mapper and read viewmodel
=> Changed user repo, read mapper and read viewmodel

Core/ViewModels/User/UserReadViewModel.cs, DataAccess/Repositories/UserRepository.cs, WebApi/AutoMapper/UserMappers/UserReadMapper.cs
Included specialization on reading a User
=> Included specialization on reading a User

Application/Services/ProcedureService.cs, Core/Entities/Procedure.cs, Core/Interfaces/Services/IProcedureService.cs, Core/ViewModels/ProcedureViewModels/ProcedureCreateViewModel.cs, WebApi/AutoMapper/Configurations/ApplicationMappersConfiguration.cs, WebApi/AutoMapper/ProcedureMappers/ProcedureCreateMapper.cs, WebApi/Controllers/ProcedureController.cs
Added abuility to assign specializations during creation
=> Refactored create procedure

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, Core/Interfaces/Services/IUserService.cs, DataAccess/Repositories/UserRepository.cs, WebApi/Controllers/UserController.cs
Added functionality to get users by the specified role
=> Added functionality to get users by the specified role

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, Core/Interfaces/Services/IUserService.cs, Core/ViewModels/User/UserReadViewModel.cs, DataAccess/Repositories/UserRepository.cs, Host/Program.cs, WebApi/AutoMapper/UserMappers/UserReadMapper.cs, WebApi/Controllers/UserController.cs
Changed doctor retrieval logic to include specializations
=> Changed doctor retrieval logic to include specializations

WebApi/AutoMapper/UserMappers/UserReadMapper.cs
Made reading User.BirthDate  in local timezone
=> Made reading User.BirthDate  in local timezone

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, Core/Interfaces/Services/IUserService.cs, DataAccess/Repositories/UserRepository.cs, WebApi/Controllers/UserController.cs
Created doctor filtration by specialization
=> Created doctor filtration by specialization

Core/ViewModels/ProcedureViewModels/ProcedureReadViewModel.cs, Tests/WebApi.Test/Fixtures/ProcedureControllerFixture.cs, Tests/WebApi.Test/ProcedureControllerTest.cs, WebApi/AutoMapper/Configurations/ApplicationMappersConfiguration.cs, WebApi/AutoMapper/ProcedureMappers/ProcedureReadMapper.cs, WebApi/AutoMapper/ProcedureMappers/ProcedureSpecEnumerableMapper.cs, WebApi/Controllers/ProcedureController.cs
Completed procedure controller tests, refactored viewModels again
=> Procedure controller tests

Core/ViewModels/User/UserReadViewModel.cs, WebApi/AutoMapper/UserMappers/UserReadMapper.cs
Edited UserReadViewModel and UserReadMapper
=> Edited UserReadViewModel and UserReadMapper

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, DataAccess/Repositories/UserRepository.cs, Tests/Application.Test/Fixtures/UserServiceFixture.cs, Tests/Application.Test/UserServiceTests.cs, Tests/WebApi.Test/Fixtures/UserControllerFixture.cs, Tests/WebApi.Test/UserControllerTests.cs
Edited unit-tests and repository
=> Edited unit-tests and repository

WebApi/AutoMapper/UserMappers/UserCreateMapper.cs
Made a method static in UserCreateMapper
=> Made a method static in UserCreateMapper

Tests/Application.Test/UserServiceTests.cs, Tests/WebApi.Test/UserControllerTests.cs
=> Edited User unit-tests

Application/Services/UserProfilePictureService.cs, Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserProfilePictureRepository.cs, DataAccess/DataAccess.csproj, DataAccess/Repositories/Configuration/ApplicationRepositoriesConfiguration.cs, DataAccess/Repositories/UserProfilePictureRepository.cs, Host/Configurations/SystemServicesConfiguration.cs, Tests/Application.Test/UserServiceTests.cs
Created UserProfilePictureRepository
=> Created UserProfilePictureRepository

Application/Services/UserProfilePictureService.cs, Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserProfilePictureRepository.cs, Core/Interfaces/Services/IUserService.cs, Core/Models/CollateParameters.cs, DataAccess/DataAccess.csproj, DataAccess/Repositories/Configuration/ApplicationRepositoriesConfiguration.cs, DataAccess/Repositories/UserProfilePictureRepository.cs, Host/Configurations/SystemServicesConfiguration.cs, Tests/Application.Test/UserServiceTests.cs, WebApi/Controllers/UserController.cs
=> Added orderBy functionality

Tests/Application.Test/UserServiceTests.cs, Tests/WebApi.Test/UserControllerTests.cs
=> Fixed user unit-tests

Core/Extensions/IQueryableExtensions.cs, DataAccess/Repositories/Configuration/ApplicationRepositoriesConfiguration.cs, Host/Configurations/SystemServicesConfiguration.cs, Host/Middleware/ApplicationMiddlewareConfiguration.cs, Host/Middleware/ExceptionMiddleware.cs, Tests/WebApi.Test/ExceptionControllerTests.cs, Tests/WebApi.Test/Fixtures/ExceptionControllerFixture.cs, WebApi/Controllers/ExceptionController.cs
=> Resolved test's conflicts

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, DataAccess/Repositories/UserRepository.cs, Tests/Application.Test/UserServiceTests.cs, WebApi/AutoMapper/UserMappers/UserUpdateMapper.cs
Changed GetByRoleAsync to search for multiple roles
=> Changed GetByRoleAsync to search for multiple roles

Application/Services/UserService.cs, Core/Interfaces/Repositories/IUserRepository.cs, DataAccess/Repositories/UserRepository.cs, Tests/Application.Test/UserServiceTests.cs
=> Edited GetByRolesAsync

DataAccess/Repositories/UserProfilePictureRepository.cs
Edited user profile picture naming
=> Edited user profile picture naming
